server:
   port: 8888
spring:
   profiles:
      active: native
cloud:
   config:
      server:
         native:
            searchLocations: [classpath:/, classpath:/config, classpath:/config/licensingservice, classpath:/config/licensingservice/default]

